version: '3'

services:
  db:
    image: "postgres:9.6-alpine"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000

volumes:
  postgres-data:
